### ISSUE TITLE
KeyError: 'dur'

### ISSUE THREAD

**Issue by yiwusuorao** [SEAL-UCSB/block_compression#1]
when I carryed out python conv_profile.py 1x1.0.json,I got this question.
@F0815-s07:~/block_compression-master/speedup$ python conv_profile.py 1x1.0.json
Traceback (most recent call last):
  File "conv_profile.py", line 163, in <module>
    _, execution_time = profile(bs=64, iw=l[0], ih=l[1], ic=l[2], oc=l[3], kw=l[4], kh=l[5], bi=b[0] if b[0] > 0 else l[2], bo=b[1] if b[1] > 0 else l[3], sp=s)
  File "conv_profile.py", line 92, in profile
    gather_time = int(next(item for item in o if item['name'].startswith(u'Gather'))['dur'])
KeyError: 'dur'
timeline.json as follow:
{
            "ts": 1540801925739071,
            "id": 0,
            "ph": "s",
            "pid": 3,
            "name": "GatherV2",
            "tid": 0,
            "cat": "DataFlow"
        },
the name is  "GatherV2",but the key doesn't have an item 'dur'.
so,I modify the code to :
for item in o:
            if item['name'].startswith(u'Gather'):
                if 'dur' in item:
                     gather_time = gather_time + item['dur']
the question is sovled.
 I want to know whether the item 'dur' must exit when the name is 'GatherV2'?

**Comment by ji-u** [comment]
I think the item 'dur' does not have to exist when the name is 'GatherV2'.
It seems that tensorflow's timeline includes many other items.
Could you please load your timeline.json file with chrome browser (entering chrome://tracing and load the file) and check if the result is correct.
