### ISSUE TITLE
"blocksparse_conv_op" How does the function work?

### ISSUE THREAD

**Issue by yiwusuorao** [SEAL-UCSB/block_compression#3]
I think code " y = bs_conv(k, x)" call  the function  in "conv.py" line 507
       def __call__(self, F, I):
        assert I.get_shape()[1] == self.C
        output = blocksparse_conv_op(
            self.fprop_grid, self.bprop_grid, self.updat_grid,
            self.mpq_lut, self.dhw_lut, self.ck_lut,
            F, I, c_type=I.dtype,
            mode=0, overlapC=self.overlapC, overlapK=self.overlapK,
            C=self.C, K=self.K, DHW=self.DHW, MPQ=self.MPQ, trs=self.trs,
            magic_trs=self.magic_trs[0], shift_trs=self.magic_trs[1],
            dimF=F.get_shape().as_list(), fshare=self.fshared, bshare=self.bshared, debug=self.debug
        )
        return output

but where is the function "blocksparse_conv_op"?How does the function work?
Thanks in advance

**Comment by ji-u** [comment]
This is a function provided by blocksparse library please refer to their repo.
