### ISSUE TITLE
Is the weight tensor reordered in the forward calculation?

### ISSUE THREAD

**Issue by Moran232** [SEAL-UCSB/block_compression#5]
Hi, you mentioned in your paper that the weight matrix or tensor will be reordered according to the permutations. 
While  in the code sparelayer.py, the weight is multiplied by the mask directly

    def forward(self, x):
          weight = torch.mul(self.weight, self.mask)
          return F.linear(x, self.weight, self.bias)

that is why?

**Comment by ji-u** [comment]
When you get the permutation, you should reorder the weight tensor according to it, the input to that layer and the output of that layer also need to reorder at runtime according to the permutation.

The correct process should be

	w = w[alpha, beta]
	b = b[beta]

	def forward(self, x):
		x = x[alpha]
		w = torch.mul(w, mask)
		y = F.linear(x, w, b)
		return y[beta^-1]

My code is used for fine-tuning, so instead of permuting the weight and input/output, I only permute the mask.
	
	mask = mask[alpha^-1, beta^-1]

	def forward(self, x):
		w = torch.mul(w, mask)
		return F.linear(x, w, b)

That is what you see, the permutation of the mask is implemented in the end of compress.py

**Comment by Moran232** [comment]
Thank for your reply.
So I have to calculate the x = x[alpha] and y[beta^-1]  myself.
Can you explain how to get the permutations alpha and beta? ( I guess it's by the 'orders' returned from compress.py)

Acctually, I am trying to reproduce the experiments on LeNet5(MNIST). I noticed that the block-size in Figure4(a) is from 16 to 128. Can you tell me which layer you prunned with this figure as the weight tensor of the first two conv layers are the size of 1x6x5x5 and 6x16x5x5.

According to the code in compress.py, the X is reshaped by block_nums and block_sizes: 
###
    ......
    X = torch.abs(X).cuda()
    dim_sizes = X.size() 
    num_dims = len(dim_sizes)
    block_sizes = [bs if bs > 0 else ds for bs, ds in zip(block_sizes, dim_sizes)]  #eg 64x32x3x3
    block_nums = [int((ds - 1) / bs) + 1 for bs, ds in zip(block_sizes, dim_sizes)]
    ...
    block_sums = X.view(*tuple(itertools.chain.from_iterable((bn, bs) for bn, bs in zip(block_nums, 
    block_sizes))))

It seems that the block_size (set by the json file) should be a factor of the X's dim_size, 
e.g.  when pruning alexnet,  the  block_size  for last layer is [40, 32, 0, 0]. 
       the weight tensor is 1000x4690 then we have the block_nums=25x128 
       so the weight wensor(X) can be reshaped with 40x25x32x128. 
So I am confused how it works for the Lenet5 under the block size of 16, 32, 64 and 128. Besides, the weight tensorf of the Liner layer in Lenet5 is 120x400, 84x120 and 10x84

**Comment by ji-u** [comment]
The permutations are the return values of compress.py

For all our experiments, we ensure that each layer has at least two blocks (As we clarified in the paper). So small layers usually have a constant block size, no matter which blocks size we choose. The block size only takes effects for large layers.

**Comment by Moran232** [comment]
So the block_size for each layer should be a factor of the X’s dim_size right?
or the block_sums will rasie error in the compress.py 
###
    ......
    X = torch.abs(X).cuda()
    dim_sizes = X.size() 
    num_dims = len(dim_sizes)
    block_sizes = [bs if bs > 0 else ds for bs, ds in zip(block_sizes, dim_sizes)]  #eg 64x32x3x3
    block_nums = [int((ds - 1) / bs) + 1 for bs, ds in zip(block_sizes, dim_sizes)]
    ...
    block_sums = X.view(*tuple(itertools.chain.from_iterable((bn, bs) for bn, bs in zip(block_nums, 
    block_sizes))))

And whta is the pruning ratio for the Lenet5?

**Comment by ji-u** [comment]
Yes, the block size for each layer should be a factor of dim size. But you can use zero-padding if you want to use other block size.

The pruning ratio is the given pruning ratio, we use 0.1~0.9 as shown in the figure.

In addition, the LeNet and MNIST experiments are done by @liangling76 , I just provide the compress.py file for him. So I couldn't answer more implementing details about the two experiments.
